### ISSUE TITLE
Automatic screen rotation

### ISSUE THREAD

**Issue by retki** [brianhorn/Tunerly#14]
Please add support for auto-rotating the screen

**Comment by brianhorn** [comment]
This was disabled deliberately to ensure no unwanted rotations happen as when tuning your instrument, you quickly lay down your phone on your lap or just any object near you which can easily trigger unwanted rotations. I believe for a tuning app making unwanted rotations impossible is more beneficial than adding auto screen rotation support.

If you want to build yourself a version with auto rotation just remove the line

`android:screenOrientation="portrait"` in `AndroidManifest.xml` (although the tuning arrows would probably overlap with the current note then).
