### ISSUE TITLE
Texts are blocked on the about page

### ISSUE THREAD

**Issue by yuhuitech** [brianhorn/Tunerly#21]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the about page, **the last part of the texts could not be seen fully, because this page is not scrollable**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.0.5, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts on the about page, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app
3.click the three vertical dots at the top-right corner of the main page, then click the about button on the popup panel
4.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/130622497-0eb20b7d-926f-4292-a3ba-c0cf072668f4.png" alt="copy" width="250"/>

**Environment**

1. Version of Tunerly: 1.0.5
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by brianhorn** [comment]
Hi there, thanks a lot for your efforts in reporting this and the corresponding pull request- I am currently on vacation and will get to this some time in early September.

**Comment by yuhuitech** [comment]
OK! That would be lovely. I am looking forward to your response later. Hope you have a great vacation!  :)

**Comment by brianhorn** [comment]
Fixed in version 1.0.6
