### ISSUE TITLE
Please add full step down for guitar 

### ISSUE THREAD

**Issue by garawaa** [brianhorn/Tunerly#23]
Feature suggestion

**Comment by ShrekhavingabadDay** [comment]
Hi garawaa!

I left a comment on this issue:
https://github.com/brianhorn/Tunerly/issues/24

It would help if you'd do the work of transcribing the tuning to frequencies so I can add it more easily.

Have a great day!

**Comment by brianhorn** [comment]
Added full step down tuning in 78ce3ec, will upload the update later in the day
