### ISSUE TITLE
Add string number at a side of the tuner

### ISSUE THREAD

**Issue by Porrumentzio** [brianhorn/Tunerly#4]
For indicating which string you are playing. This could be helpful for not well known afinations.

**Comment by brianhorn** [comment]
I'm not sure the use outweighs the "cons" - If you are using another tuning than standard you very probably know which string to tune to which note. I'm not sure I personally ever benefited from the string number next to the note now that I think about it (which is probably why I didn't think about including it). 

The con for me would be more stuff on screen - I'm trying to keep the UI and information it displays as minimal and clean as I can and adding the string number next to the note is not something I would prefer over just which note you currently tune to.

**Comment by Porrumentzio** [comment]
My opinion is that there are many starting musicians that do not know which string has which tuning. For that reason, I think that if the number of string is not indicated, all scales selected to tune to are almost like the chromatic (I mean, they don't say you if that string is okay, but if that sound, no matter which string, is tuned to a note)

**Comment by brianhorn** [comment]
The way chromatic tuner differs from choosing an instrument and a corresponding tuning is that for the latter, it only shows the note of the closest string (octaves are considered, so for example if your low E string on Guitar is tuned about a step lower and you play it, it will not show "D is in tune", but "you need to tune up so E is in tune"). 

But yes, that means that if you for example just restrung your Guitar and don't know which string to tune to which note and also don't intuitively know the range in which the string you want to tune to lies it would be difficult to tune your instrument. 

However again I don't see this as a decisive problem in practice - if you don't tune to standard tuning you are surely "advanced" enough to know which notes to tune to, and even if you are a beginner who tunes to standard tuning you learn the note names very early on anyway just about anywhere (if you have a teacher he will quickly make you learn it, if you learn on your own by tabs it's written on there, if you learn by video tutorials sentences like "play the second fret on the d string" are mentioned all the time and so on).  Knowing the note names of the strings of your instrument is the most basic vocabulary to communicate about your instrument, even if you are only being taught or teach yourself and don't exchange with eg a teacher or friend. Plus you don't even need to know it as long as your Guitar is not completely out of tune. Therefore I find leaving it out in favor of a cleaner UI to be a better choice.
