### ISSUE TITLE
Let user choose th A4 Hz

### ISSUE THREAD

**Issue by Porrumentzio** [brianhorn/Tunerly#6]
I suppose the Hz for A4 reference is currently 440, but I think it would be great to be able to change that with an option in settings.

**Comment by brianhorn** [comment]
Yes, the current A4 reference is set to 440Hz. I thought about adding that option shortly before I released it as currently is, however at that point the way I implemented mapping pitch to notes (which in hindsight is definitely not optimal) is not compatible with offering this option. 

And to be honest I'm too lazy to rewrite it for this feature :grinning:

**Comment by Porrumentzio** [comment]
Great haha
