### ISSUE TITLE
Pitch detection algorithms

### ISSUE THREAD

**Issue by pterodactylus42** [brianhorn/Tunerly#9]
Hey there, great respect for your great Tuner! Feel free to check out mine... Did you play around with the pitch detection algorithm implementations? I'm having issues with the mpm ... basically it's a great algorithm which gives a smooth detection for musical instruments - check out the rack tuner from guitarix:
https://sourceforge.net/projects/guitarix/files/gxtuner/
but unfortunately, when i select it the app mysteriously crashes after a undefined time period. had to remove it from the menu. in the sourcecode of tarsos 2.4 android version it says
"
 * MPM runs in real time with a standard 44.1 kHz sampling rate.
"
but changing to 44.1 kHz does not fix the issue.

so long, have fun coding audio :-)

**Comment by brianhorn** [comment]
Hi, thanks! I remember in the beginning trying out all the algorithms that Tarsos offers - currently the app uses `FFT_YIN`, I'm not 100% sure how I ended up using that one anymore but I believe I didn't find there to be a noticeable difference for the apps purposes between the different algorithms. 

I just tried using MPM instead to see if it works for me, and it does. You can take a look at my parameters at the beginning of `MainActivity.kt´.
